# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flashpca_internal <- function(X, stand, ndim, maxiter, tol, seed, verbose, do_loadings, return_scale) {
    .Call('flashpcaR_flashpca_internal', PACKAGE = 'flashpcaR', X, stand, ndim, maxiter, tol, seed, verbose, do_loadings, return_scale)
}

flashpca_plink_internal <- function(fn, stand, ndim, maxiter, block_size, tol, seed, verbose, do_loadings, return_scale) {
    .Call('flashpcaR_flashpca_plink_internal', PACKAGE = 'flashpcaR', fn, stand, ndim, maxiter, block_size, tol, seed, verbose, do_loadings, return_scale)
}

scca_internal <- function(X, Y, lambda1, lambda2, ndim, stand_x, stand_y, mem, seed, maxiter, tol, verbose, num_threads, useV, Vinit) {
    .Call('flashpcaR_scca_internal', PACKAGE = 'flashpcaR', X, Y, lambda1, lambda2, ndim, stand_x, stand_y, mem, seed, maxiter, tol, verbose, num_threads, useV, Vinit)
}

